<?php

namespace App\Services\Schedule;

use App\Models\Clients\Clients;
use App\Models\Schedule\Schedule;
use App\Repositories\Schedule\ScheduleRepository;
use App\Services\Client\ClientService;

class ScheduleService extends ScheduleRepository
{

    /**
     * @param $date
     * @return \Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model[]
     */
    public function verifyIfIsAvailable($date)
    {
        return Schedule::where('schedule',$date)
            ->get();
    }

    /**
     * @param array $attributes
     * @return \Exception|\Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model
     */
    public function create(array $attributes = [])
    {
        try{
            $client = Clients::where('phone',$attributes['phone'])
                ->first();

            if(is_null($client)){
                $clientService = new ClientService();
                $clientService->create($attributes);
            }

            $client = Clients::where('phone',$attributes['phone'])
                ->first();

            $attributes['client_id'] = $client->id;

            return parent::create($attributes); // TODO: Change the autogenerated stub
        }catch (\Exception $exception){
            return $exception;
        }
    }

}
