<?php

namespace App\Services\Client;

use App\Repositories\Client\ClientRepository;

class ClientService extends ClientRepository
{
    /**
     * @param array $attributes
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Model
     */
    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
